### PR TITLE
(Resolve #184) Cool minimalist logos for Gitmoney

### LINKED ISSUE #184: Create a two tone logo
**Current Payout: 4,874,000 satoshis / ~ $20** [Proof](https://live.blockcypher.com/btc/address/3GYXHi1GrnTRLQfrgRivj2VWdJh3tMtdRD)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Job Details:**

1. Simple font (here's a good example of what we mean by that - https://media.balsamiq.com/files/company/balsamiq-logo-noborder-print.png 
2. Two-toned (git - black [#000000] // money- green [#66a878]
3. In the pull request with the completed work please provide us with a .psd & .png of the logo. Please submit a logo with clear resolution. 
4. Have fun, put some of your touches on it! This is a community project after all!!!

### PR DESCRIPTION
**Pull request by rocktshyp**
Resolves #184
Bitcoin Address: 1sF7GoCq1zrMg8xeKHjuafgAq5brQcy3X
Description: Finally made some cool but unique minimalist logos for GitMoney that are high-resolution and in both PNG/PSD!
Here's a link to the entire folder: https://app.box.com/s/amkp9jtwuojt7vp9lymc2ytyg8tdteav
The markdown file that I want to add is merely links to the singular files for the different logos.

### CODE REVIEW

**Comment by matthewjamesr** [comment]
@rocktshyp good work on your logo designs, I vote for your PR to be accepted.

**Comment by masonicGIT** [comment]
@matthewjamesr @wbinns 

I like this one a lot. Very clean and simple. I would prefer that the Bitcoin logo be removed, but I think I can remove that myself if we agree that that's a point of contention (don't want to hassle the rocket ship).

@rocktshyp - Great work here!

**Comment by rocktshyp** [comment]
Yeah, looking back in retrospect I agree. I can update the PSD files with a version without the Bitcoin logo

**Comment by rocktshyp** [comment]
Lol! I took out the Bitcoin logo for you. I agree, it looks way better.

**Comment by masonicGIT** [comment]
Thanks so much! These look great.

**Comment by chuck-nasty** [comment]
@rocktshyp thanks for making these for us!

**Comment by masonicGIT** [comment]
@rocktshyp - https://twitter.com/gitmoneyco They're up!

**Comment by matthewjamesr** [comment]
The power of git money :)

**Pull request merged**
