### PR TITLE
Consolidate web assets into public folder (keep web root clean)

### PR DESCRIPTION
**Pull request by araaku**
Resolve: #128
Bitcoin address: 3FjobKg82mY6xaMvMvwzND3YES37AcUFzf
Descript: Consolidated web assets into public folder.

### CODE REVIEW

**Comment by masonicGIT** [comment]
@wbinns - Does this create any conflicts for us on the website? Our endpoint for the bounty image is no longer being used, so its ok from the server side.

**Comment by araaku** [comment]
It may create conflicts as the new files has been added and existing files has been modified since the last commit. I can restructure it again if it still needs to be merged.

**Comment by wbinns** [comment]
@araaku Thanks for working on this. It's okay, we can handle this on our side.

**Comment by wbinns** [comment]
You should see some new bitcoin in your wallet. Thanks for your help on this. :)

**Comment by araaku** [comment]
Thanks a lot!

**Pull request closed without merging**
