### PR TITLE
adding swedish translation for review

### LINKED ISSUE #143: Translate home page to Swedish
**Current Bounty: 23,978 bits / ~ $10** [Proof](https://live.blockcypher.com/btc/address/32oCEzjGTuHRJi3VmuDEHXmE3473XBzD4d)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Bounty Details:**
Translate text in index.html to Swedish and add to /translations/ folder as swedish.html

### PR DESCRIPTION
**Pull request by cponeill**
Resolves #143 
Bitcoin Address: 1GG3sg3Etp5VjfV5j2S2fZ9DpNsXqAKtWA
Description: Translated text in index.html to Swedish and added to /translations/ folder as swedish.html for review

### CODE REVIEW

**Comment by jimmycallin** [comment]
Fellow Swede here. This translation is quite bad and seems to have been machine translated. I would not accept the pull request.

**Comment by chuck-nasty** [comment]
Jimmy you interesting in contributing? We can take urs and then have t reviewed as well. Thanks for tbe input! Cheers

**Comment by jimmycallin** [comment]
@chuck-nasty Sure, I'll find time in a few days. Brb!

**Comment by chuck-nasty** [comment]
Thanks and looking forward to it!!

**Pull request closed without merging**
