### PR TITLE
adding pt-br translation

### LINKED ISSUE #137: Translate home page to Portuguese
**Current Bounty: 23,928 bits / ~ $10** [Proof](https://live.blockcypher.com/btc/address/35R19oBaSCUyGDgWPoYd4PeTq8kJCaMj78)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Bounty Details:**
Translate index.html to Portuguese and add to /translations/ folder as portuguese.html

### PR DESCRIPTION
**Pull request by hems**
Resolves #137
Bitcoin Address: 1JNkknaPhrYewodyQS7GY31Pa8rQQSWsd5
Description: Unfortunately i couldn't preview the page, but i took a lot of care with the markup and the portuguese itself. My native portuguese is from Brazil so you might want to open another issue for someone to duplicate and review from a Portugal's perspective.

__*NOTE*__:
I have simplified the translation since "However you choose to git money" and "It's completely up to you" sounded very redundant in portuguese

### CODE REVIEW

**Comment by masonicGIT** [comment]
Thank you @hems!

**Comment by masonicGIT** [comment]
@hems - It seems that we did not send out your payment properly - since our pr and pr-br translations referred to the same issue. We're very sorry, we went ahead and manually sent your bounty here: https://tradeblock.com/bitcoin/tx/5d33adfb4f5d138f67eda39ccc107cb83003483d5fc35c7bf27d94d5a42ec3a0.

**Comment by hems** [comment]
congratulations for such project

**Comment by masonicGIT** [comment]
@hems - Thanks for being a part of it :-)

**Pull request merged**
