### PR TITLE
Simplified Chinese Translation

### LINKED ISSUE #139: Translate home page to Simplified Chinese
**Current Bounty: 24,202 bits / ~ $10** [Proof](https://live.blockcypher.com/btc/address/34unjUAdt3gJwzsqigNRdfv4e52tkF7i3b)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Bounty Details:**
Translate index.html to Simplified Chinese and add to /translations/ folder as chinese.html

### PR DESCRIPTION
**Pull request by accraze**
If you are submitting a pull request to collect a bounty, please submit it in
the following example format:

Resolves #139 
Bitcoin Address: 12E31FZd3u5D5de6xSRAzezMG14fLeCHo5
Description: Chinese translations and alt tags, etc.... much more accurate than #246

### CODE REVIEW

**Comment by angrob** [comment]
You take my work make some minor changes and put it up as your work? Seriously?

**Comment by accraze** [comment]
no @angrob I did not take your work, I did this on my own. My translation is different than yours and did not see your pull request until after pushing mine up. I will remove this since you are unhappy.

**Comment by angrob** [comment]
Not particular unhappy... you can just review my translation and make your contribution later if you think there are issues with it.

**Comment by wbinns** [comment]
@accraze @angrob Thank you both for working on this. I've sent you both some bitcoin.

**Pull request closed without merging**
