### PR TITLE
Update twitter.md

### LINKED ISSUE #178: Tweet/Retweet Git Money
**Current Payout: 1,211 bits / ~ $0.50** [Proof](https://live.blockcypher.com/btc/address/3EXAUum8frhJWuALjfaHi6V3c4Pmuac8og)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Job Details:**
Retweet the tweets in social/twitter.md, write a new tweet supporting Git Money, and add a link to it as the newest tweet in the list.

### PR DESCRIPTION
**Pull request by djeep**
Resolves #178
Bitcoin Address: 1DaDpprmZY2E7DV4FGa77MXSfSn7PnUiz5
Description: Retweeted all previous tweets and appended my tweet.

### CODE REVIEW

**Comment by chuck-nasty** [comment]
hey man - I just sent you a tweeter follow request (your tweets are protected!) - I just wanted to verify the bounty work and then i'll get this moving, cheers man!

**Comment by djeep** [comment]
Right on, follow request accepted amigo.

**Comment by chuck-nasty** [comment]
Thanks for being patient & for the tweets!

**Comment by djeep** [comment]
trevcole@gmail.com has invited you to join the world of INGRESS.

Ingress Logo Google Play Store Logo Apple App Store Logo


The Ingress has begun.Life seems "normal" but your world is being  
infiltrated. A mysterious energy has been unlocked by a team of scientists  
in Europe and is spreading around the world. The origin and purpose of this  
force is unknown, but some researchers believe it is influencing the way we  
think. We must control it or it will control us.There are two factions to  
choose from. The Enlightened seek to spread this influence. The Resistance  
struggle to protect what's left of our humanity.


The World is the GameMove through the real world using your Android or iOS  
device and the Ingress app to discover and tap sources of this mysterious  
energy, acquire objects from Portals to aid in your quest, deploy tech to  
capture territory, and ally with other players to advance the cause of the  
Enlightened or the Resistance.StrategyThe struggle is being played out  
globally. Track the progress of players around the world, plan your next  
steps, and communicate with others using the Intel Map.What is the Niantic  
Project?Is this just a game? An Investigation Board filled with cryptic  
clues and secret codes awaits. Powerful secrets and game tech are there to  
be unlocked.Bring your FriendsThe struggle to save the planet spans the  
entire world. Groups of people acting together can be more effective than  
individuals acting alone. And cooperation across neighborhoods, cities, and  
countries will be needed to achieve the ultimate victory.Want to see  
Ingress in Action?Check out the Ingress Report for the latest updates and  
intel. Or watch these great tutorials to help get started. Ingress Report  
on YouTube Ingress Tutorials

Ingress App Screen Image


Ingress Help Center Visit Player Help Center to learn more.

Ingress Channel Subscribe to the Official Ingress YouTube Channel.

Ingress Google+ Page Follow us on the Official Ingress Google+ Page.

**Pull request merged**
