### PR TITLE
Checked Japanese

### LINKED ISSUE #212: Review Japanese Translation
**Current Payout: 1,439,954 satoshis / ~$6** [Proof](https://live.blockcypher.com/btc/address/3G6UA3zGk7RJ3WV7Pgfy6Zte63q8FLC7gF)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Job Details:**
Please review the Japanese translation of the Git Money homepage (translations/japanese.html) and make corrections as necessary.

### PR DESCRIPTION
**Pull request by paulhandy**
Resolves #212 
Bitcoin Address: 1C4CCS8c9VKA1Kkq14G5NDgtwCUhqTA1e6
Description: Reviewed Japanese translation, made minor changes in wording.

### CODE REVIEW

**Comment by dabura667** [comment]
Overall, the translation was good to start with.

The fixes you have done are some of the bigger ones, and some smaller ones I found are really judgment calls imo

There was one (technically) incorrect kanji you missed. (Most Japanese would miss it) I'll tip u changetip if you can find it. :-)

ACK

**Comment by paulhandy** [comment]
Now you have me on a hunt...

**Comment by chuck-nasty** [comment]
ILL UP THAT TIP PAUL YOU MUST FIND THIS

**Comment by paulhandy** [comment]
I agree, I saw quite a few smaller things, but I didn't see them as getting in the way of the message. Are you referring to 超える vs 越える?

**Comment by masonicGIT** [comment]
Thanks a lot @paulhandy & @dabura667 :-). The payment goes out immediately.

**Comment by dabura667** [comment]
Actually, you were right about koeru, but the one that I am looking at will show up in the dictionary as what it is here... But the reason why is because the kun-yomi of the correct kanji is not considered "joyo kanji reading" so schools have adopted the easier, less correct kanji.

Huuuge hints there, so no guarantees on the tip anymore.

Good luck :-)

**Pull request merged**
