### PR TITLE
Resolves #208

### LINKED ISSUE #208: Review French Translation
**Current Payout: 1,439,539 satoshis / ~$6** [Proof](https://live.blockcypher.com/btc/address/3EypTbNuLjGmhQumZwb16xjrmZWzr6TYLC)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Job Details:**
Please review the French translation of the Git Money homepage (translations/french.html) and make corrections as necessary.

### PR DESCRIPTION
**Pull request by romjpn**
Resolves #208 
Bitcoin address : 1FdomsLftfiEJZ9DXcp6rzjfXBjbZEsAQb
Description: Reviewed and translated your website to French.

### CODE REVIEW

**Comment by wbinns** [comment]
@romjpn Hello, could you please fix your merge conflicts?

**Comment by romjpn** [comment]
Hello,
I can't see were are the conflicts. Did I messed up somewhere ? I can't see a way to fix it.

**Comment by aiouy** [comment]
Native french speaker here. I can vouch for this translation.

**Comment by masonicGIT** [comment]
Hey @romjpn - We're seeing a merge conflict error, just pull the latest changes in and make sure it merges cleanly and you will be good to go :-)

**Comment by romjpn** [comment]
Tried to resolve it ! I hope it works out !

**Pull request merged**
