### PR TITLE
Resolves #196

### LINKED ISSUE #178: Tweet/Retweet Git Money
**Current Payout: 1,211 bits / ~ $0.50** [Proof](https://live.blockcypher.com/btc/address/3EXAUum8frhJWuALjfaHi6V3c4Pmuac8og)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Job Details:**
Retweet the tweets in social/twitter.md, write a new tweet supporting Git Money, and add a link to it as the newest tweet in the list.

### LINKED ISSUE #196: Post a Video on YouTube about Git Money
**Current Payout: 1,445,087 satoshis / ~$6** [Proof](https://live.blockcypher.com/btc/address/3E2bTv6mqD2uVe4re4JQZgo5DJDN4tUf55)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Job Details:**
Post a video on YouTube about Git Money (a minimum of 90 seconds) with the tags "Bitcoin" and "Blockchain" and add a link to it in social/youtube.md.

**See https://github.com/21hackers/git-money/blob/master/social/about-git-money.md for info about this project to help get you started.**

### PR DESCRIPTION
**Pull request by mjrodovalho**
Resolves #196 

Bitcoin Address: 1B1J1TXFvivKxzRTRCpfHwEf1XLsYkoEWn
Description: Video on youtube about Gitmoney, in portuguese.

### CODE REVIEW

**Comment by masonicGIT** [comment]
Hello @mjrodovalho - Would you be able to do separate pull requests for each of these :-). For the logo, we received another request with multiple form factors and file types that we will be going with, hope thats ok. 

Also thanks for doing a video in Portuguese, that's really awesome.

Thanks!

-Mason

**Comment by mjrodovalho** [comment]
Ok @masonicGIT changed the pull request.

**Comment by mjrodovalho** [comment]
Do I have to close this pull request?

**Comment by mjrodovalho** [comment]
Hello @masonicGIT I cant find a way to separate pull requests for each of these

**Comment by wbinns** [comment]
@mjrodovalho Hello, if you split this into two different branches, it will be easier to do two separate pull requests. Also, thanks again for your contributions!

Could you also please fix your merge conflicts? Just let me know if you need help!

**Comment by wbinns** [comment]
I just sent you bitcoin for that awesome video. Thank you. :)

**Pull request closed without merging**
