### PR TITLE
added Swedish translation (Resolves #143)

### LINKED ISSUE #143: Translate home page to Swedish
**Current Bounty: 23,978 bits / ~ $10** [Proof](https://live.blockcypher.com/btc/address/32oCEzjGTuHRJi3VmuDEHXmE3473XBzD4d)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Bounty Details:**
Translate text in index.html to Swedish and add to /translations/ folder as swedish.html

### PR DESCRIPTION
**Pull request by sahuk**
Resolves #143
Bitcoin Address: 18TdWdApt7X8tquLdZ275e1MguhTDWtvKd
Description: Swedish translation of the html.

### CODE REVIEW

**Comment by masonicGIT** [comment]
@sahuk - Hey this looks really great. Thanks so much for doing this. Would you mind taking care of the metadata at the top too? Such as the description and title.

**Comment by wbinns** [comment]
@sahuk Hello, I just wanted to follow-up to see if you could please update the meta-data, as @masonicGIT mentioned.

**Comment by sahuk** [comment]
@wbinns , @masonicGIT , how's this? I left the `<html lang="en">` untouched as the other translations did.

**Comment by wbinns** [comment]
@sahuk Looks perfect now that you fixed the meta description! Merging this so you automatically get paid. :) Thanks for the contribution!

**Pull request merged**
